### ISSUE TITLE
Feature request - output string formatting. Uppercase/lowercase etc.

### ISSUE THREAD

**Issue by PawelWozniak** [bhughes339/vscode-replacerules#46]
I want to make rules that will format APEX (Salesforce case insensitive language similar to JAVA), code that was written without care about casing. Code works but code highlighting in VSCode won't and we have also code conventions introduced.

So I made a rule:
```
        "CF Map,List,Set with big letter":{
            "find": "(map|list|set)<",
            "replace": "$1<",
            "languages": ["apex", "apex-anon"]
        }
```
And want to have as output Map or List or Set.

I was experimenting with your plugin code and found that it is possible to influence output after replacement. But I stuck at the point of adding settings options for that. I wanted to have an additional entry "casing" with values uppercase, lowercase, first upper etc.
I have no idea yet about VSCode plugins development, would you be so kind and add output string processing?

**Comment by bhughes339** [comment]
String post-processing is a bit out of scope for this project. Case transformation is not available in Javascript RegEx, and being open to adding specific options like "casing" would probably result in feature creep. VSCode also has a builtin "Transform to Title Case" command that works well.

**Comment by mgorelkin** [comment]
I know this is marked as out-of-scope, but this is suuuch a needed feature. I've reverted to copy-n-paste into VSCode find-n-replace because my use-cases very often require case-changes (e.g. auto-generating getters and setters on properties, but for 'prop', 'getProp' requires me to uppercase the 'P'). Would highly appreciate re-consideration of tackling this. Thanks in advance!
