### ISSUE TITLE
Apply rules to selection only?

### ISSUE THREAD

**Issue by pauloneill** [bhughes339/vscode-replacerules#54]
Does your extension work against the selection if there is one, or the entire document otherwise?

Full disclosure: I haven't tried this not could I find any documentation about it.... 😞

**Comment by bhughes339** [comment]
Yup, a rule will be applied to a selection (or multiple selections) if they exist; otherwise it will be applied to the entire document. It's actually in the first line of the README:
- A "rule" is one or more search/replace patterns that can be applied to the entire document, or one or more selections of text.

**Comment by pauloneill** [comment]
Thanks Bill

Best regards,
Paul
p:  (08) 9200 4431
e:  ***@***.******@***.***>
w: www.insilico.com.au<http://www.insilico.com.au/>
Because technology should make life easier…
