### ISSUE TITLE
[feature request] move cursor if line grows before it

### ISSUE THREAD

**Issue by atnbueno** [bhughes339/vscode-replacerules#7]
I know I asked for the cursor not to move in https://github.com/bhughes339/vscode-replacerules/issues/4 😁 but it _looks_ weird when (again, same rules and testing code) with these rules:
```
"replacerules.rules": [
    {
        "name": "OpenSCAD typos",
        "find": [
            "\\bcentre(\\s*=)",
            "(linear_extrude.+\\b)h(\\s*=.+)"
        ],
        "replace": [
            "center$1",
            "$1height$2"
        ]
    }
]
```
applied to this text:
```
linear_extrude(centre = true, convexity = 10, twist = -500, h = 10)
    cylinder(r1=9.5, r2=19.5, centre=true, h=15);
```
and when the cursor is after the "h =" of the first line, this happens:

![](http://www.mundoplus.tv/atnbueno/replacerules_move_cursor_feature-request.gif)

(five characters are added, so the cursor does not stay after the "=", at column 69, but five characters before, at column 64)

Would it be possible to avoid this (understandable but weird) shift?

**Comment by bhughes339** [comment]
I noticed this when fixing #4 in fact. It seems like a VSCode bug, since I could not find a method of making the cursor "sticky" after an edit. Interestingly, it works fine when you do a manual find and replace through the editor (Ctrl+H). I'll keep my eye on this, but since I'm still new to extensions, I likely won't get to it for a while.

**Comment by bhughes339** [comment]
Worked on some improvements today, and one of my goals is to make the replace function of Replace Rules work as similarly to the native Find and Replace as possible. I just wanted to document some observations regarding the cursor movement:

When a Find and Replace is done through the VSCode interface, each replacement is registered by the editor one at a time. For example, running the replacement `/\d/test/gm` over the text "1,2,3" would look something like this:

- "1" is replaced with "test"
- "2" is replaced with "test"
- "3" is replaced with "test"
- All three edits are validated and executed in the document

In Replace Rules, all replacements are done on a copy of the selection string (or line string) in memory before being registered by the editor. Using the same example from above:

- "1,2,3" is replaced with "test,test,test"
- The single edit is validated and executed in the document

The main consequence of the way Replace Rules handles replacements is documented here by @atnbueno. Basically, the VSCode API (specifically, the edit-builder) handles edits one at a time, and uses the current cursor position to determine where to move the cursor, if at all. An edit to a text section to the left of the cursor will cause the cursor to shift depending on the length of the replacement string. This can be observed by modifying the `find` string from the original post in this issue. If we run the replacement `/(linear_extrude.+\b)h(\s*=)/$1height$2/gm` on the text "linear_extrude(centre = true, convexity = 10, twist = -500, h = 10)" with the cursor initially being right after "h =", here's the result:
Before:
![image](https://user-images.githubusercontent.com/16418739/37623664-debb2b20-2b9b-11e8-90fd-cee0232c5094.png)
After:
![image](https://user-images.githubusercontent.com/16418739/37623697-fbcdc6be-2b9b-11e8-922b-e27c44f1538f.png)

Because all of the edits were done to the left of the cursor, it shifted to the right correctly. If we modify the `find` portion of the replacement to look for one extra space, the edit will span across characters to the left AND right of the cursor. Using the same example as above, but with the replacement `/(linear_extrude.+\b)h(\s*= )/$1height$2/gm`:
Before:
![image](https://user-images.githubusercontent.com/16418739/37623735-199e2292-2b9c-11e8-88ac-cba18c50e72e.png)
After:
![image](https://user-images.githubusercontent.com/16418739/37623753-25d16362-2b9c-11e8-9154-78db1dccdfff.png)

The original issue submitted by @atnbueno is actually the intended behavior, since the edit ends up spanning characters to the left and right of the cursor. In order for the cursor to properly shift, the `find` string in the Replace Rule will need to be modified to "(linear_extrude.+\\b)h(\\s*=)" which will still not work until I rewrite the code. I will be updating the extension with these principles in mind so I can more accurately emulate the native Find and Replace functionality.
